apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
      - name: apigw
        image: ghcr.io/frank1192/apigtest:latest
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: apigw-service
spec:
  selector:
    app: apigw
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30080
  type: NodePort