# cachetadacontrucha-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cachetadacontrucha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cachetadacontrucha
  template:
    metadata:
      labels:
        app: cachetadacontrucha
    spec:
      containers:
      - name: cachetadacontrucha
        image: ghcr.io/frank1192/cachetadacontrucha:latest
        ports:
        - containerPort: 7080

---

apiVersion: v1
kind: Service
metadata:
  name: cachetadacontrucha
spec:
  selector:
    app: cachetadacontrucha
  ports:
    - protocol: TCP
      port: 7080
      targetPort: 7080
  type: ClusterIP
